sudo: false
language: node_js
node_js:
  - 12 # use nodejs v12 LTS
cache:
  apt: true
  directories:
    - node_modules
branches:
  only:
    - main # build master branch only
script:
  - hexo clean  #清除
  - hexo generate #生成
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main
  local-dir: public
env:
  - TRAVIS_NODE_VERSION="12.4.0"
install:
  - nvm install ${TRAVIS_NODE_VERSION}
  - nvm alias default ${TRAVIS_NODE_VERSION}
  - npm install
